name: my-first-action
run-name: @${{ github.actor }}
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "hello world"
      - name: Print Bye
        run: echo "Bye..."
